### ISSUE TITLE
Infinite loop when using autosave

### ISSUE THREAD

**Issue by jfly** [aldeed/meteor-autoform-bs-datepicker#11]
This is very similar to https://github.com/aldeed/meteor-autoform-bs-datetimepicker/issues/3.

**Comment by FatBoyXPC** [comment]
Are there any updates on this? I would also like to take advantage of autosave and the datepicker!

**Comment by lynchem** [comment]
+1 Very frustrating bug in an otherwise wonderful package

**Comment by aldeed** [comment]
Fixed in latest

**Comment by mibcadet** [comment]
Hi,

I'm using 1.2.0 version (due to lots of SimpleSchemas I would have to update to make collection2 2.0.0 compatible).
Is this fix also in 1.2.0? From my POV atm this loop issue with autosave still exists.

**Comment by aldeed** [comment]
@mibcadet 1.2.0 and 2.0.0 are the same other than which version of autoform they depend on, so it should be fixed in both. If not, can you submit a new issue with some code that reproduces the issue you are seeing.
